server:
    port: 9527


spring:
    application:
        name: microserviceloud-zuul-gateway                         #对外暴漏的微服务名称

eureka:
    server:
        enable-self-preservation: true #false=禁用自我保护机制、true=开启自我保护、不推荐false，（默认=true开启—）
    instance:
        instance-id: gateway-9527.com # 自定义zuul相关的服务名称信息
        prefer-ip-address: true #显示eureka监控页面链接的ip地址
    client:
         service-url:
              # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的的地址查询服务和注册服务，等价于： http://localhost:7001/eureka/  （单机版）
              defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  # 集群版


#路由映射
#http://myzuul.com:9527/dyh/microserviceloud-dept/dept/get/3  改为  http://myzuul.com:9527/dyh/mydept/dept/get/3
#相当于 对外暴漏一个虚拟地址
zuul:
   prefix: /dyh  #前缀统一加/dyh 如：http://myzuul.com:9527/dyh/mydept/dept/get/3
   ignored-services: "*" #屏蔽真实对外暴漏的名称、如果有多个可以用* 实列：ignored-services: "*"
   routes:
       mydept.serviceId: microserviceloud-dept  #将microserviceloud-dept 对外暴漏名称通过路由改为/mydept/
       mydept.path: /mydept/**
       

info:
    app.name: dyh-microservicecloud
    company.name: www.dyh.cn
    build.artifactId: microservicecloud-zuul-gateway-9527
    build.version: 1.0-SNAPSHOT